### PR TITLE
Support Compose Multiplatform

### PR DESCRIPTION
**Pull request by jmseb3**
# Summary

Support Compose Multiplatform target
(Android/iOS/JVM/JS/WasmJS)

In version "1.7.0-beta02" or higher of compose, support **GraphicsLayer** per platform

https://www.jetbrains.com/help/kotlin-multiplatform-dev/whats-new-compose-170.html#graphicslayer-a-new-drawing-api

## Preview
capturable preview per platform

### Android
aos_preview

### iOS
ios_preview

### JVM(Desktop)
jvm_preview

### JS
js_preview

### WasmJS
wasm_preview

## What's Change

- Migration gradle to gradle.kts
- use version catalog(.toml)
- capturable lib support cmp
- update example app(/composeApp)

## Checklist

- [x] Build and linting is passing.
- [x] This change is not breaking existing flow of a system.
- [ ] I have written test case for this change.
- [ ] This change is tested from all aspects.
- [x] Implemented any new third-party library _(Which not existed before this change)_.

### CODE REVIEW

**Comment by PatilShreyas** [comment]
This is nice @jmseb3 😃, thanks for raising a PR. Will take a look 👍🏻

**Comment by jmseb3** [comment]
I saw in #217 that there are no plans to convert for compose Multiplatform

If so, can I manage the project by uploading it to maven for compose Multiplatform?

**Comment by PatilShreyas** [comment]
Sure you can @jmseb3 👍🏻

**Comment by jmseb3** [comment]
thank you

**Pull request closed without merging**
